#!/bin/sh
 
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

mkdir -p ${HOME}/.kube
mv ./scripts/config ${HOME}/.kube/config
kubectl version
kubectl get nodes

kubectl apply -f ./deploy/kubernetes/complete-demo.yaml